# Configuration file for new_songs_enjoyer
# This file contains application settings (API keys should be in .env file)

# Music tags to search for recommendations
default_tags:
  - "chill"
  - "ambient"
  - "lofi"

# Number of tracks to recommend daily
num_tracks: 20

# API settings
api:
  limit_per_tag: 100
  base_url: "https://ws.audioscrobbler.com/2.0/"

# Output settings
output:
  directory: "output"
  history_filename: "music_history.json"
  daily_playlist_format: "playlist_{timestamp}.json"  # Now uses detailed timestamp

# Display settings
display:
  show_fetching_progress: true
  language: "fr"  # fr for French messages, en for English

# Logging settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# SoundCloud integration settings
soundcloud:
  enabled: false  # Set to true to enable SoundCloud integration
  playlist_name: "new_songs_enjoyer - Discovery"
  auto_import: false  # Automatically import playlists to SoundCloud

# Platform filtering settings
platform_filtering:
  enabled: true  # Enable filtering against user's liked songs from music platforms
  soundcloud:
    enabled: true  # Filter against SoundCloud liked tracks
    oauth_token: "${SOUNDCLOUD_OAUTH_TOKEN}"  # OAuth token from browser cookies
  spotify:
    enabled: false  # Filter against Spotify liked tracks (optional)
    client_id: "${SPOTIFY_CLIENT_ID}"  # Spotify app client ID
    client_secret: "${SPOTIFY_CLIENT_SECRET}"  # Spotify app client secret
    access_token: "${SPOTIFY_ACCESS_TOKEN}"  # User access token for liked songs
